# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Analyze and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.1"

          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Test app
        run: flutter test

#      - name: Start release build
#        run: flutter build apk
#      - run: ls build/app/outputs/flutter-apk
#
#
#      - name: Upload to firebase distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.APP_ID}}
#          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
#          groups: Internal
#          file: build/app/outputs/flutter-apk/app-release.apk